### PR TITLE
tsconfig.json format fixed

### PR DESCRIPTION
**Pull request by Tralafarlaw**
Error at build on newer versions of ts
```
> Build failed with 1 error:
node_modules/tiny-case/tsconfig.json:1:0: error: Unexpected end of file
```

### CODE REVIEW

**Comment by Simonpedro** [comment]
The same's happening to me, would be nice to have this merged @jquense. Thank you!

```sh
> remix dev

> node_modules/tiny-case/tsconfig.json:1:0: error: Unexpected end of file
    1 │ 
      ╵ ^


Build failed with 1 error:
node_modules/tiny-case/tsconfig.json:1:0: error: Unexpected end of file
💿 Built in 194ms
```

**Comment by Simonpedro** [comment]
@Tralafarlaw In case it helps, for now, you can just use v1.0.0-alpha.1, which doesn't depend on `tiny-case`

**Comment by johannschopplich** [comment]
@jquense This would help a lot, since `tiny-case` breaks Netlify builds for me at the moment.

**Comment by johannschopplich** [comment]
Quick fix for everyone reading this, using pnpm:

```json
"pnpm": {
  "overrides": {
    "tiny-case": "npm:change-case@^4.1.2"
  }
}
```

**Comment by jquense** [comment]
thanks, updated

**Pull request merged**
